services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: esluser
      POSTGRES_PASSWORD: eslpass
      POSTGRES_DB: esldb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esl_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esluser -d esldb"]
      interval: 5s
      timeout: 5s
      retries: 10

  esl_app:
    build: .
    ports:
      - "${RANDOM_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=postgresql://esluser:eslpass@postgres:5432/esldb
      - PORT=3000
      - RUST_LOG=info
    depends_on:
      - postgres
    networks:
      - esl_network
    restart: unless-stopped
    volumes:
      - ./static:/app/static

volumes:
  postgres_data:

networks:
  esl_network:
    driver: bridge
